modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bundleapi"
version = "${version}"
displayName = "BundleAPI"
authors = "TheRedBrain"
description = '''
An API for mods that allows easy addition of bundles with custom sizes and filtered content.
'''
logoFile = "icon.png"

[[dependencies.bundleapi]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bundleapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
