# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
# TODO change to 2.0.0 for 1.21.11
mod_version = 1.1.0
maven_group = com.github.TheRedBrain
archives_base_name = bundle-api
loom_version=1.16-SNAPSHOT

# Minecraft properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
additional_minecraft_versions=

# Dependencies
yumi_version=1.0.0-beta.1+1.21.11

fabric_loader_version = 0.19.5
fabric_api_version=0.141.2+1.21.11
yarn_mappings_patch_neoforge_version = 1.21+build.6

neoforge_version = 21.11.45
neoforge_loader_version = 11.0.0