modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bundleapi"
version = "${version}"
displayName = "BundleAPI"
authors = "TheRedBrain"
description = '''
An API for mods that allows easy addition of bundles with custom sizes and filtered content.
'''
logoFile = "icon.png"

[[dependencies.bundleapi]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bundleapi]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bundleapi.mixins.json"
