name: Publish
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build and publish with Gradle
        run: ./gradlew build publishMods
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CURSEFORGE_PROJECT_ID: ${{ vars.CURSEFORGE_PROJECT_ID }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          MODRINTH_PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
          GH_REPO: ${{ github.event.repository.name }}